# Generated by Django 4.2.11 on 2026-04-27 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='date',
        ),
        migrations.AddField(
            model_name='studysession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
